#cloud-config
#set hostname
fqdn: npm
#update all packages
package_upgrade: true

#set up users
users:
  - name: klaus
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO1QYZfvmPFlaxFVaOeSsGo4RgK+Yl7coaC8pb9xk/Vk klaus@macairlet.agnoletti.net
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5PtFc36246Dihi2k2Rnf6pAhglTkdSBJa4O2ihu7eUwPz0kVmCpuHrVG307K9VFK0LcZsuMrSOMWxVJtbiN6/s/lJXt/+5kH7ypdM9xoUeSYLqdBtnsEdhefI2SrhQZK+JiLWKvZ1MjbJBmhurGsI2AoejQxN47T6w4GsMTV4HvPbkjx/3VGQKZcLI4J9MDU1F8JAHk2iQ1F/wc7OuWctLM7jL3FusWLPtjITti+fg3r7soiJilW1+lZ4ce9axh2vtDyHSnupK5w4iIVQYrCrPiVqhIwan+LNl1P3NM6sUFQlMjJJocohD3TtmfFeIHcPK1r3Zoi/Pe8y8yq5W2s+ugnUFbkF2kRdsNNOHsnIkAcU5+FSieBknPyE1YL1akQlqRskkT6DR502TCsNYWeLwquT8H0NxST9suoodqt3tWospxDuiTNEfDdGI+ptBWOKZiDqWVZRCdsfNKnOgFcrwEH8RKZ0Frbj7/YEJ0zm6+NBuYZV9Ij+qzneDVV+RMmK0Ulvei0HtAcz6iXOtMDyfPloyL1/R80vutU1tW+yZ3tkoFHA14/hhhokBd5ruEowjj1TPD0yCcFffKWybBONWe2HxF5LEqEqgjpNWT/3U1/bQ3ov7YXnX59p7Z0Xl3HQNWZ2JFDMuovTrRBkHCmObkm6MPSgJ9LUBMXZxWZbbQ== klaus@flaplet
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTVR/bTtTx4YxU+Hm87a+XF49XMEMvGJVd4p1IVUXUIuggoj+74C+17dq3wAShSn8QKu6PowNp9JFwrN3OaNV2R2xUpCiQqL1u/a9m53f1hD4WWsLcVMwL7CiJzqpXP0NbixTcFBJKiLV0u0dMC0y1LGBK0IKrJ66gccwxiHlD1XOdUWC+ip01dBuEebx0wwkZsXviwPBveZzEMsCI1dXgfaPowotRYThVC4jnczefu9gRSHC+372QvRyVhCrGStwElIrp0saa5jzP8X/cc/eGN+rn52tUiFNFABQraPOZC75nL/+PVy9dyiouKyWXk20lbARD9j/RPF8HKPH4HgMB klaus@nuclet 
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMItt5ehLmdPaNzxYw7PcxV2hQyD14MAgIQsF3RxWrAB klaus@slimey
  #install needed packages
packages:
#requirements for docker.io
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
#install docker.io
  - docker-ce
  - docker-ce-cli
  - containerd.io
runcmd:
  - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg #add docker.gpgp keys
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null #add lines to sources.list